apiVersion: v1
kind: Service
metadata:
  name: $DOCS_NAME
  labels:
    app: $DOCS_NAME
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: $DOCS_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DOCS_NAME
  labels:
    app: $DOCS_NAME
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $DOCS_NAME
  template:
    metadata:
      labels:
        app: $DOCS_NAME
    spec:
      containers:
      - name: $DOCS_NAME
        image: gcr.io/postgres-ai/docs$TAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: URL
            value: $URL
          - name: BASE_URL
            value: $BASE_URL
